spring.application.name=demo



#postgres
spring.datasource.url=jdbc:postgresql://localhost:5433/yerscompany
spring.datasource.username=postgres
spring.datasource.password=yerscompany
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=8097
